"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Copy, Loader2, LogIn, Package, Percent, Server, ShoppingCart, Users } from "lucide-react";
import { supabase } from "@/lib/supabase";
import Link from "next/link";

type Product={id:string;name:string;description:string|null;price:number;max_quantity:number;image_url:string|null};
type ServerState={server_name:string;server_address:string;online:boolean;players_online:number;players_max:number;player_names:string[];minecraft_version:string|null;last_seen_at:string}|null;
type DiscountInfo={valid:boolean;discountCode:string|null;discountPercent:number;discountAmount:number;subtotal:number;amount:number;verificationDiscountApplied?:boolean;verificationDiscountPercent?:number;verificationPurchasesRemaining?:number;codeDiscountPercent?:number};

export default function AevonSMPPage(){
 const [products,setProducts]=useState<Product[]>([]),[server,setServer]=useState<ServerState>(null),[selected,setSelected]=useState<Product|null>(null),[ign,setIgn]=useState(""),[qty,setQty]=useState(1),[method,setMethod]=useState<"paypal"|"gcash">("paypal"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[loggedIn,setLoggedIn]=useState(false),[copied,setCopied]=useState(false),[discountCode,setDiscountCode]=useState(""),[discount,setDiscount]=useState<DiscountInfo|null>(null),[discountBusy,setDiscountBusy]=useState(false),[discountMessage,setDiscountMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch('/api/aevonsmp/products',{cache:'no-store'});if(r.ok){const b=await r.json();setProducts(b.products||[]);setServer(b.server||null)}},[]);
 useEffect(()=>{void load();const timer=setInterval(load,10000);void supabase?.auth.getSession().then(({data})=>setLoggedIn(Boolean(data.session)));return()=>clearInterval(timer)},[load]);
 const subtotal=useMemo(()=>selected?Number(selected.price)*qty:0,[selected,qty]);
 const total=discount?.valid?discount.amount:subtotal;
 useEffect(()=>{
  let cancelled=false;
  async function refreshPricing(){
   setDiscount(null);setDiscountMessage("");
   if(!selected||!loggedIn||!supabase)return;
   const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)return;
   const r=await fetch('/api/aevonsmp/discount/validate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({productId:selected.id,quantity:qty,discountCode:''})});
   const b=await r.json();if(cancelled||!r.ok)return;
   if(b.verificationDiscountApplied){setDiscount(b);setDiscountMessage(`Fully Verified benefit applied — 50% off. ${Number(b.verificationPurchasesRemaining)} discounted purchase${Number(b.verificationPurchasesRemaining)===1?'':'s'} remaining for this product after this order.`)}
  }
  void refreshPricing();return()=>{cancelled=true};
 },[qty,selected,loggedIn]);
 async function applyDiscount(){if(!selected||!discountCode.trim())return;setDiscountBusy(true);setDiscountMessage("");const {data}=await supabase!.auth.getSession();const token=data.session?.access_token;if(!token){setDiscountBusy(false);setDiscountMessage("Please sign in before applying a discount code.");return}const r=await fetch('/api/aevonsmp/discount/validate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({productId:selected.id,quantity:qty,discountCode:discountCode.trim()})});const b=await r.json();setDiscountBusy(false);if(!r.ok){setDiscount(null);setDiscountMessage(b.error||'Invalid discount code.');return}setDiscount(b);setDiscountMessage(b.verificationDiscountApplied&&Number(b.codeDiscountPercent||0)<50?`${b.discountCode} linked. Your Fully Verified 50% benefit gives the better price.`:`${b.discountCode} applied — ${Number(b.discountPercent)}% off.`)}
 async function checkout(){if(!selected||!ign.trim())return;setBusy(true);setMessage("");const {data}=await supabase!.auth.getSession();const token=data.session?.access_token;if(!token){setBusy(false);setMessage("Please sign in before placing an order.");return}const url=method==='paypal'?'/api/aevonsmp/orders/paypal/create':'/api/aevonsmp/orders/gcash';const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({productId:selected.id,minecraftIgn:ign.trim(),quantity:qty,discountCode:discount?.valid?discount.discountCode:null})});const b=await r.json();setBusy(false);if(!r.ok){setMessage(b.error||'Could not create order.');return}if(method==='paypal'&&b.approveUrl){window.location.href=b.approveUrl;return}setMessage(`GCash order ${b.order?.order_code} created. Once an admin approves the payment, the reward is queued automatically.`)}
 async function copyIp(){await navigator.clipboard.writeText(server?.server_address||'aevonsmp.online');setCopied(true);setTimeout(()=>setCopied(false),1400)}
 return <div className="pageWrap asmpPage">
  <section className="asmpHero"><div><p className="eyebrow">AEVONSMP</p><h1>Play. Shop. Receive it in-game.</h1><p className="muted">See who is online, browse server products, and send purchased rewards straight to your Minecraft IGN.</p><div className="asmpHeroActions"><button onClick={copyIp} className="primaryBtn"><Copy size={15}/>{copied?'Copied!':server?.server_address||'aevonsmp.online'}</button><a className="secondaryBtn" href="#products"><ShoppingCart size={15}/> Browse Products</a></div></div><div className={`asmpServerCard ${server?.online?'online':'offline'}`}><div className="asmpServerTop"><Server size={24}/><div><small>SERVER STATUS</small><strong>{server?.online?'ONLINE':'OFFLINE'}</strong></div></div><div className="asmpServerStats"><div><Users size={16}/><span><b>{server?.players_online??0}</b>{server?.players_max?` / ${server.players_max}`:''} Players</span></div><div><span>{server?.minecraft_version||'Minecraft'}</span></div></div></div></section>
  <section className="asmpPlayersSection"><div className="sectionHeading"><div><p className="eyebrow">LIVE PLAYERS</p><h2>Currently Playing</h2></div><span className="asmpLivePill">Updates every 10 seconds</span></div>{server?.online&&server.player_names?.length?<div className="asmpPlayerGrid">{server.player_names.map(n=><div className="asmpPlayer" key={n}><img src={`https://mc-heads.net/avatar/${encodeURIComponent(n)}/48`} alt=""/><span>{n}</span></div>)}</div>:<div className="emptyCard"><Users size={20}/><span>{server?.online?'No players are online right now.':'The server is currently offline or the bridge has not reported yet.'}</span></div>}</section>
  <section id="products" className="asmpProductsSection"><div className="sectionHeading"><div><p className="eyebrow">AEVONSMP PRODUCTS</p><h2>Server Store</h2><p className="muted smallMuted">Choose a product, quantity, and the Minecraft IGN that should receive it.</p></div></div><div className="asmpProductGrid">{products.map(p=><article className="asmpProductCard" key={p.id}>{p.image_url?<img src={p.image_url} alt={p.name}/>:<div className="asmpProductPlaceholder"><Package size={34}/></div>}<div className="asmpProductBody"><h3>{p.name}</h3><p>{p.description||'AevonSMP server product.'}</p><div className="asmpProductFooter"><strong>₱{Number(p.price).toFixed(2)}</strong><button className="primaryBtn" onClick={()=>{setSelected(p);setQty(1);setMessage('');setDiscountCode('');setDiscount(null);setDiscountMessage('')}}><ShoppingCart size={14}/> Order</button></div></div></article>)}</div>{!products.length&&<div className="emptyCard"><Package size={22}/><span>No AevonSMP products are published yet.</span></div>}</section>
  {selected&&<div className="asmpModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="asmpCheckoutModal"><div className="sectionHeading"><div><p className="eyebrow">CHECKOUT</p><h2>{selected.name}</h2></div><button className="secondaryBtn" onClick={()=>setSelected(null)}>Close</button></div>{!loggedIn&&<div className="notice info"><LogIn size={16}/><span>You need to sign in before purchasing. <Link href="/login">Login here</Link>.</span></div>}<label>Minecraft IGN<input value={ign} onChange={e=>setIgn(e.target.value)} placeholder="Klioh_" maxLength={17}/><span className="fieldHint">The reward goes to this exact Minecraft player name. Bedrock dot-prefix names are accepted.</span></label><label>Quantity<input type="number" min="1" max={selected.max_quantity} value={qty} onChange={e=>setQty(Math.max(1,Math.min(selected.max_quantity,Number(e.target.value)||1)))}/></label><label>Discount Code <div className="discountInputRow"><input value={discountCode} onChange={e=>{setDiscountCode(e.target.value.toUpperCase());setDiscount(null);setDiscountMessage('')}} placeholder="AEVON10-XXXXXXXX"/><button type="button" className="secondaryBtn" disabled={discountBusy||!discountCode.trim()||!loggedIn} onClick={applyDiscount}>{discountBusy?<Loader2 size={14} className="spin"/>:<Percent size={14}/>} Apply</button></div>{discountMessage&&<span className={`fieldHint ${discount?.valid?'discountSuccess':'discountError'}`}>{discountMessage}</span>}</label><label>Payment Method<select value={method} onChange={e=>setMethod(e.target.value as any)}><option value="paypal">PayPal — automatic confirmation</option><option value="gcash">GCash — admin verification</option></select></label><div className="asmpPriceBreakdown"><div><span>Subtotal</span><b>₱{subtotal.toFixed(2)}</b></div>{discount?.valid&&<div className="discountLine"><span>{discount.verificationDiscountApplied?`Fully Verified Discount (${discount.discountPercent}%)`:`Discount (${discount.discountPercent}%)`}</span><b>-₱{discount.discountAmount.toFixed(2)}</b></div>}<div className="asmpCheckoutTotal"><span>Total</span><strong>₱{total.toFixed(2)}</strong></div></div>{message&&<div className="notice info"><CheckCircle2 size={16}/><span>{message}</span></div>}<button className="primaryBtn asmpCheckoutBtn" disabled={busy||!loggedIn||!ign.trim()} onClick={checkout}>{busy?<Loader2 size={15} className="spin"/>:<ShoppingCart size={15}/>} {busy?'Creating order…':method==='paypal'?'Continue to PayPal':'Create GCash Order'}</button></div></div>}
 </div>
}
