"use client";
import {useEffect,useState} from 'react';
import {BadgeCheck,Camera,Copy,KeyRound,Mail,Package,Percent,ShieldCheck,UploadCloud,UserRound,Wallet} from 'lucide-react';
import {supabase} from '@/lib/supabase';

export default function AccountPage(){
 const [user,setUser]=useState<any>(null),[p,setP]=useState<any>(null),[owned,setOwned]=useState<any[]>([]),[nick,setNick]=useState(''),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[currentPass,setCurrentPass]=useState(''),[legal,setLegal]=useState(''),[idFile,setIdFile]=useState<File|null>(null),[selfie,setSelfie]=useState<File|null>(null),[msg,setMsg]=useState(''),[discount,setDiscount]=useState<any>(null),[discountOpen,setDiscountOpen]=useState(false),[copied,setCopied]=useState(false);
 useEffect(()=>{(async()=>{if(!supabase)return;const {data}=await supabase.auth.getUser();if(!data.user)return;setUser(data.user);setEmail(data.user.email||'');const t=(await supabase.auth.getSession()).data.session?.access_token||'';const [profileResponse,{data:up},discountResponse]=await Promise.all([fetch('/api/account/me',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}),supabase.from('user_plugins').select('id,access_type,created_at,plugins:plugin_id(id,name,slug,version,price)').eq('user_id',data.user.id).order('created_at',{ascending:false}),fetch('/api/account/discount-code',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'})]);const account=await profileResponse.json().catch(()=>({}));const pr=profileResponse.ok?account.profile:null;setP(pr);setNick(pr?.nickname||'');setOwned(up||[]);if(discountResponse.ok)setDiscount(await discountResponse.json());})();},[]);
 async function token(){return (await supabase!.auth.getSession()).data.session?.access_token||''}
 async function patchProfile(body:any){const r=await fetch('/api/account/profile',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error);setP({...p,...b.profile});return b.profile}
 async function saveNick(){try{setMsg('Saving…');await patchProfile({nickname:nick});setMsg('Nickname updated. Your next nickname change is available in 30 days.')}catch(e:any){setMsg(e.message)}}
 async function avatar(f:File){if(!supabase||!user)return;try{setMsg('Uploading profile picture…');const r=await fetch('/api/account/avatar',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({fileName:f.name,contentType:f.type,size:f.size})});const b=await r.json();if(!r.ok)throw Error(b.error);const {error}=await supabase.storage.from('profile-avatars').uploadToSignedUrl(b.path,b.token,f,{contentType:f.type});if(error)throw error;await patchProfile({avatar_url:b.publicUrl});setMsg('Profile picture updated.')}catch(e:any){setMsg(e.message||'Could not update profile picture.')}}
 async function updateEmail(){if(!supabase||!user)return;const next=email.trim();if(!next)return setMsg('Enter a valid email address.');if(next.toLowerCase()===(user.email||'').toLowerCase())return setMsg('That is already your current email address.');setMsg('Updating email…');const {error}=await supabase.auth.updateUser({email:next});setMsg(error?error.message:'Email update requested. Please confirm the change using the verification email sent by Supabase.')}
 async function updatePass(){try{setMsg('Updating password…');const r=await fetch('/api/account/password',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({currentPassword:currentPass,newPassword:pass})});const b=await r.json();if(!r.ok)throw Error(b.error);setPass('');setCurrentPass('');setMsg('Password updated successfully.')}catch(e:any){setMsg(e.message||'Could not update password.')}}
 async function signedUpload(file:File,kind:'id'|'selfie'){const r=await fetch('/api/account/verification',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({kind,contentType:file.type,size:file.size})});const b=await r.json();if(!r.ok)throw Error(b.error);const {error}=await supabase!.storage.from('verification-documents').uploadToSignedUrl(b.path,b.token,file,{contentType:file.type});if(error)throw error;return b.path}
 async function submitVerification(){if(!idFile||!selfie||legal.trim().length<3)return setMsg('Please complete your legal name, valid ID, and selfie.');try{setMsg('Securely uploading verification documents…');const [idDocumentPath,selfiePath]=await Promise.all([signedUpload(idFile,'id'),signedUpload(selfie,'selfie')]);const r=await fetch('/api/account/verification',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({legalName:legal,idDocumentPath,selfiePath})});const b=await r.json();if(!r.ok)throw Error(b.error);setP({...p,verification_status:'pending'});setMsg('Verification submitted. An admin will review your application.')}catch(e:any){setMsg(e.message)}}
 async function copyCode(){if(!discount?.code?.code)return;await navigator.clipboard.writeText(discount.code.code);setCopied(true);setTimeout(()=>setCopied(false),1400)}
 if(!user)return <div className="pageWrap accountHub"><div className="accountPanel"><h1>My Account</h1><p>Please sign in to manage your account.</p></div></div>;
 return <div className="pageWrap accountHub">
  <div className="accountHero"><div className="accountAvatar">{p?.avatar_url?<img src={p.avatar_url}/>:<UserRound/>}<label><Camera size={14}/><input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&avatar(e.target.files[0])}/></label></div><div><span>AEVON MEMBER</span><h1>{p?.nickname||'My Account'} {p?.verification_status==='verified'&&<BadgeCheck className="verifiedBadge"/>}</h1><p>{p?.verification_status==='verified'?'Fully Verified Account':'Manage your profile, security, purchases, and verification.'}</p></div></div>{msg&&<div className="accountNotice">{msg}</div>}
  <div className="accountGrid"><section className="accountPanel"><h2><UserRound/> Profile & Nickname</h2><label>Public nickname<input value={nick} onChange={e=>setNick(e.target.value)} maxLength={32}/></label><p className="fieldHelp">Only your nickname is shown publicly. It can be changed once every 30 days.</p><button className="primaryBtn" onClick={saveNick}>Update Nickname</button><label className="avatarUpload">Profile picture<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&avatar(e.target.files[0])}/></label></section>
  <section className="accountPanel"><h2><KeyRound/> Login & Security</h2><label><Mail size={13}/> Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="secondaryBtn" onClick={updateEmail}>Update Email</button><label>Current password<input type="password" value={currentPass} onChange={e=>setCurrentPass(e.target.value)} placeholder="Current password"/></label><label>New password<input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="At least 8 characters"/></label><button className="secondaryBtn" onClick={updatePass}>Change Password</button><p className="fieldHelp">Sensitive account changes use your authenticated Supabase session. Email changes require confirmation.</p></section></div>

  <section id="discount-code" className={`accountPanel discountAccountPanel ${discountOpen?'open':''}`}>
   <button className="discountAccountToggle" onClick={()=>setDiscountOpen(v=>!v)}><div><Percent/><span><b>Discount Code</b><small>{discount?.code?`${Number(discount.code.discount_percent)}% customer discount · ${Number(discount.code.commission_percent)}% commission`:'No discount code has been assigned to this account.'}</small></span></div><strong>{discountOpen?'HIDE':'VIEW'}</strong></button>
   {discountOpen&&<div className="discountAccountBody">{discount?.code?<><div className="discountCodeHero"><div><span>YOUR DISCOUNT CODE</span><strong>{discount.code.code}</strong><small className={`discountStatus ${discount.code.status}`}>{discount.code.status.toUpperCase()}</small></div><button className="secondaryBtn" onClick={copyCode}><Copy size={14}/>{copied?'Copied!':'Copy Code'}</button></div><div className="discountStatsGrid"><div><span>Discount</span><strong>{Number(discount.code.discount_percent)}%</strong></div><div><span>Players Used</span><strong>{discount.stats?.uniquePlayers||0}</strong></div><div><span>Paid Uses</span><strong>{discount.stats?.uses||0}</strong></div><div><span>Commission Rate</span><strong>{Number(discount.code.commission_percent)}%</strong></div><div><span>Commission Balance</span><strong>₱{Number(discount.stats?.balance||0).toFixed(2)}</strong></div><div><span>Lifetime Earned</span><strong>₱{Number(discount.stats?.lifetimeEarned||0).toFixed(2)}</strong></div></div><div className="discountExplanation"><Wallet size={17}/><p>Your commission is credited only after a purchase using your code is successfully paid or approved. Commission is calculated from the final amount paid after the customer discount.</p></div></>:<div className="emptyCard"><Percent size={20}/><span>An administrator has not assigned a discount code to your account yet.</span></div>}</div>}
  </section>

  <section id="purchased" className="accountPanel purchasedPanel"><h2><Package/> Purchased Plugins</h2>{owned.length?owned.map((x:any)=><a key={x.id} href={`/plugins/${x.plugins?.slug}`} className="purchasedRow"><div><strong>{x.plugins?.name}</strong><span>v{x.plugins?.version||'1.0.0'} · {x.access_type==='purchase'?'Purchased':x.access_type==='grant'?'Granted':'Admin access'}</span></div><b>VIEW RESOURCE →</b></a>):<p className="muted">No owned plugins yet.</p>}</section>
  <section id="verification" className="accountPanel verificationPanel"><div className="verificationTitle"><ShieldCheck/><div><span>IDENTITY VERIFICATION</span><h2>Verify Account</h2></div><b className={`verifyState ${p?.verification_status||'unverified'}`}>{String(p?.verification_status||'unverified').replace('_',' ').toUpperCase()}</b></div>{p?.verification_status==='verified'?<div className="verifiedSuccess"><BadgeCheck/> Your identity has been reviewed and approved by an Aevon Marketplace administrator. Your public nickname now receives the Fully Verified badge. Verified accounts also receive 50% off the first 5 successful purchases of each eligible product across AevonSMP and AevonPlugins.</div>:p?.verification_status==='pending'?<div className="pendingVerification">Your application is under review. Verification is never automatic; an administrator must approve it.</div>:<><div className="verificationInstructions"><strong>Before submitting</strong><ol><li>Enter your legal full name exactly as it appears on your ID.</li><li>Upload a clear valid ID showing your name and photo. JPG, PNG, WEBP, or PDF; maximum 8 MB.</li><li>Upload a clear recent selfie showing your face.</li><li>Only submit your own documents. Your documents are private and are not shown on your public profile.</li><li>After submission, an administrator will manually review the application.</li></ol></div><label>Legal full name<input value={legal} onChange={e=>setLegal(e.target.value)} placeholder="As shown on your valid ID"/></label><div className="verificationUploads"><label><UploadCloud/> Valid ID<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setIdFile(e.target.files?.[0]||null)}/><span>{idFile?.name||'Choose ID document'}</span></label><label><UploadCloud/> Selfie<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setSelfie(e.target.files?.[0]||null)}/><span>{selfie?.name||'Choose selfie'}</span></label></div><button className="primaryBtn" onClick={submitVerification}>Submit for Admin Verification</button></>}</section>
 </div>
}
