"use client";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Edit3, Loader2, Plus, RefreshCw, Trash2, XCircle } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Product={id:string;name:string;description:string|null;price:number;reward_command:string;command_mode:"once"|"per_quantity";required_free_slots:number;max_quantity:number;image_url:string|null;status:string;sort_order:number};
type Order={id:string;order_code:string;customer_email:string;product_name:string;quantity:number;amount:number;minecraft_ign:string;payment_method:string;payment_status:string;delivery_status:string;created_at:string};
const blank={name:"",description:"",price:"",reward_command:"",command_mode:"once",required_free_slots:"0",max_quantity:"64",image_url:"",status:"published",sort_order:"0"};

export default function AdminAevonSMPStore(){
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[form,setForm]=useState<any>(blank),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string>("");
 const token=async()=> (await supabase?.auth.getSession())?.data.session?.access_token||"";
 const load=useCallback(async()=>{const t=await token();if(!t)return;const [p,o]=await Promise.all([fetch("/api/admin/aevonsmp/products",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),fetch("/api/admin/aevonsmp/orders",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"})]);if(p.ok)setProducts((await p.json()).products||[]);if(o.ok)setOrders((await o.json()).orders||[]);},[]);
 useEffect(()=>{void load()},[load]);
 const edit=(p:Product)=>{setEditing(p.id);setForm({name:p.name,description:p.description||"",price:String(p.price),reward_command:p.reward_command,command_mode:p.command_mode,required_free_slots:String(p.required_free_slots),max_quantity:String(p.max_quantity),image_url:p.image_url||"",status:p.status,sort_order:String(p.sort_order)})};
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");const t=await token();const r=await fetch(editing?`/api/admin/aevonsmp/products/${editing}`:"/api/admin/aevonsmp/products",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify(form)});const b=await r.json();setBusy(false);if(!r.ok){setNotice(b.error||"Could not save product.");return}setNotice(editing?"AevonSMP product updated.":"AevonSMP product created.");setEditing(null);setForm(blank);await load()}
 async function remove(id:string){if(!confirm("Delete this AevonSMP product? Existing orders keep their reward snapshot."))return;const t=await token();await fetch(`/api/admin/aevonsmp/products/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${t}`}});await load()}
 async function review(id:string,action:"approve"|"reject"){const t=await token();const r=await fetch(`/api/admin/aevonsmp/orders/${id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:"{}"});const b=await r.json();setNotice(r.ok?(action==="approve"?"GCash payment approved. Reward is queued for Minecraft delivery.":"GCash order rejected."):(b.error||"Could not update order."));await load()}
 return <section className="adminListSection asmpAdminSection">
  <div className="sectionHeading"><div><p className="eyebrow">AEVONSMP STORE</p><h2>Products & In-Game Fulfillment</h2><p className="muted smallMuted">Products execute only after confirmed payment. Commands run from console through the secure AevonSMPBridge plugin.</p></div><button className="secondaryBtn" onClick={load}><RefreshCw size={14}/> Refresh</button></div>
  {notice&&<div className="notice info"><CheckCircle2 size={16}/><span>{notice}</span></div>}
  <form className="formCard asmpProductForm" onSubmit={save}>
   <div className="sectionHeading"><h3>{editing?"Edit AevonSMP Product":"Add AevonSMP Product"}</h3>{editing&&<button type="button" className="secondaryBtn" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel edit</button>}</div>
   <div className="editorTwoCol"><label>Product Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="500 ACoins"/></label><label>Price (PHP)<input required type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label></div>
   <label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Shown to customers on the AevonSMP store."/></label>
   <label>Reward Command<input required value={form.reward_command} onChange={e=>setForm({...form,reward_command:e.target.value})} placeholder="acoins give {player} 500"/><span className="fieldHint">Placeholders: {'{player}'}, {'{quantity}'}, {'{order_id}'}, {'{product}'}. Do not include the leading /.</span></label>
   <div className="editorTwoCol"><label>Command Mode<select value={form.command_mode} onChange={e=>setForm({...form,command_mode:e.target.value})}><option value="once">Run once (use {'{quantity}'})</option><option value="per_quantity">Run once per quantity</option></select></label><label>Required Free Inventory Slots<input type="number" min="0" max="36" value={form.required_free_slots} onChange={e=>setForm({...form,required_free_slots:e.target.value})}/></label></div>
   <div className="editorTwoCol"><label>Maximum Quantity<input type="number" min="1" max="999" value={form.max_quantity} onChange={e=>setForm({...form,max_quantity:e.target.value})}/></label><label>Product Image URL<input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://... (optional)"/></label></div>
   <div className="editorTwoCol"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="published">Published</option><option value="draft">Draft</option></select></label><label>Sort Order<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label></div>
   <button className="primaryBtn" disabled={busy}>{busy?<Loader2 size={15} className="spin"/>:editing?<Edit3 size={15}/>:<Plus size={15}/>} {busy?"Saving…":editing?"Save Product":"Add Product"}</button>
  </form>
  <div className="asmpAdminGrid">{products.map(p=><article className="adminPluginRow" key={p.id}><div className="adminPluginMain"><div className="adminPluginTitleRow"><h3>{p.name}</h3><span className={`statusBadge ${p.status}`}>{p.status}</span></div><p>{p.description||"No description."}</p><code>{p.reward_command}</code><div className="pluginMeta"><span>₱{Number(p.price).toFixed(2)}</span><span>Max {p.max_quantity}</span><span>{p.required_free_slots} free slot(s)</span><span>{p.command_mode}</span></div></div><div className="adminPluginActions"><button className="secondaryBtn" onClick={()=>edit(p)}><Edit3 size={14}/> Edit</button><button className="dangerBtn" onClick={()=>remove(p.id)}><Trash2 size={14}/> Delete</button></div></article>)}</div>
  <div className="sectionHeading asmpOrdersHead"><div><h3>AevonSMP Orders</h3><p className="muted smallMuted">PayPal orders confirm automatically. GCash orders wait for admin approval.</p></div></div>
  <div className="paymentOrderList">{orders.length===0?<div className="emptyCard">No AevonSMP orders yet.</div>:orders.map(o=><div className={`paymentOrderRow ${o.payment_status}`} key={o.id}><div className="paymentOrderMain"><div className="adminPluginTitleRow"><h3>{o.product_name} × {o.quantity}</h3><span className={`orderStatus ${o.delivery_status}`}>{o.delivery_status.replaceAll("_"," ")}</span></div><code>{o.order_code}</code><p>{o.minecraft_ign} · {o.customer_email}</p><div className="pluginMeta"><span>{o.payment_method.toUpperCase()}</span><span>₱{Number(o.amount).toFixed(2)}</span><span>{o.payment_status}</span><span>{new Date(o.created_at).toLocaleString()}</span></div></div>{o.payment_method==="gcash"&&o.payment_status==="pending"&&<div className="adminPluginActions"><button className="secondaryBtn" onClick={()=>review(o.id,"reject")}><XCircle size={14}/> Reject</button><button className="primaryBtn" onClick={()=>review(o.id,"approve")}><CheckCircle2 size={14}/> Approve & Queue</button></div>}</div>)}</div>
 </section>
}
