"use client";
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {BadgeCheck,Coins,CreditCard,Loader2,Lock,MessageCircle,MessagesSquare,Plus,Send,Sparkles,Trash2,UserRound,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';

type Author={nickname?:string|null;avatar_url?:string|null;verification_status?:string|null;role?:string|null}|null;
type ReactionCounts={like:number;heart:number;laugh:number;wow:number;sad:number};
type Thread={id:string;user_id:string;title:string;body:string;status:string;is_pinned:boolean;charge_kind?:'free'|'credit';created_at:string;updated_at:string;reply_count?:number;author:Author;reaction_counts?:ReactionCounts;viewer_reaction?:string|null};
type Reply={id:string;thread_id:string;user_id:string;parent_reply_id?:string|null;body:string;created_at:string;author:Author;reaction_counts?:ReactionCounts;viewer_reaction?:string|null};
type Wallet={credits:number;free_threads_remaining:number;total_credits_purchased:number;total_threads_created:number}|null;
type Viewer={id:string|null;role:string|null};
const reactionOptions=[['like','👍','Like'],['heart','❤️','Heart'],['laugh','😂','Laugh'],['wow','😮','Wow'],['sad','😢','Sad']] as const;

function AuthorBadge({author}:{author:Author}){return <div className="forumAuthor">{author?.avatar_url?<img src={author.avatar_url} alt=""/>:<span className="forumAvatarFallback"><UserRound size={16}/></span>}<span><b>{author?.nickname||'Aevon Member'}</b><small>{author?.role==='admin'?'AEVON ADMIN':author?.verification_status==='verified'?'VERIFIED MEMBER':'AEVON MEMBER'}</small></span>{author?.verification_status==='verified'&&<BadgeCheck size={14} className="verifiedBadge"/>}</div>}

function ReactionBar({counts,current,disabled,onReact}:{counts?:ReactionCounts;current?:string|null;disabled?:boolean;onReact:(r:string)=>void}){
 return <div className="forumReactionBar">{reactionOptions.map(([key,emoji,label])=><button key={key} type="button" className={current===key?'active':''} disabled={disabled} onClick={()=>onReact(key)} title={label}><span>{emoji}</span>{(counts?.[key as keyof ReactionCounts]||0)>0&&<b>{counts?.[key as keyof ReactionCounts]}</b>}</button>)}</div>
}

export default function AevonForumPage(){
 const [threads,setThreads]=useState<Thread[]>([]),[wallet,setWallet]=useState<Wallet>(null),[viewer,setViewer]=useState<Viewer>({id:null,role:null}),[loggedIn,setLoggedIn]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [composer,setComposer]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[creditsOpen,setCreditsOpen]=useState(false),[amount,setAmount]=useState(100),[payMethod,setPayMethod]=useState<'paypal'|'gcash'>('paypal');
 const [selected,setSelected]=useState<Thread|null>(null),[replies,setReplies]=useState<Reply[]>([]),[reply,setReply]=useState(''),[replyingTo,setReplyingTo]=useState<Reply|null>(null),[threadBusy,setThreadBusy]=useState(false),[deleteBusy,setDeleteBusy]=useState(false);
 const credits=Math.floor(amount/10);
 const token=async()=> (await supabase?.auth.getSession())?.data.session?.access_token||'';
 const load=useCallback(async()=>{const t=await token();setLoggedIn(Boolean(t));const r=await fetch('/api/aevonsmp/forum/threads',{headers:t?{Authorization:`Bearer ${t}`}:{},cache:'no-store'});const b=await r.json();if(r.ok){setThreads(b.threads||[]);setWallet(b.wallet||null);setViewer(b.viewer||{id:null,role:null})}},[]);
 useEffect(()=>{void load()},[load]);
 async function openThread(t:Thread){setSelected(t);setReplies([]);setReply('');setReplyingTo(null);setThreadBusy(true);const tok=await token();const r=await fetch(`/api/aevonsmp/forum/threads/${t.id}`,{headers:tok?{Authorization:`Bearer ${tok}`}:{},cache:'no-store'});const b=await r.json();setThreadBusy(false);if(r.ok){setSelected(b.thread);setReplies(b.replies||[]);if(b.viewer)setViewer(b.viewer)}}
 async function createThread(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');const t=await token();if(!t){setBusy(false);setMessage('Please sign in before creating a forum thread.');return}const r=await fetch('/api/aevonsmp/forum/threads',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({title,body})});const b=await r.json();setBusy(false);if(!r.ok){setMessage(b.error||'Could not create thread.');if(b.needsCredits){setComposer(false);setCreditsOpen(true)}return}setTitle('');setBody('');setComposer(false);setWallet(b.wallet||wallet);setMessage('Your thread is live.');await load();if(b.thread)void openThread(b.thread)}
 async function sendReply(){if(!selected||!reply.trim())return;setThreadBusy(true);const t=await token();if(!t){setThreadBusy(false);setMessage('Please sign in to reply.');return}const r=await fetch(`/api/aevonsmp/forum/threads/${selected.id}/replies`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({body:reply,parent_reply_id:replyingTo?.id||null})});const b=await r.json();setThreadBusy(false);if(!r.ok){setMessage(b.error||'Could not post reply.');return}setReply('');setReplyingTo(null);await openThread(selected);await load()}
 async function react(target:'thread'|'reply',id:string,reaction:string){const t=await token();if(!t){setMessage('Please sign in to react to posts.');return}const url=target==='thread'?`/api/aevonsmp/forum/threads/${id}/reactions`:`/api/aevonsmp/forum/replies/${id}/reactions`;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({reaction})});const b=await r.json();if(!r.ok){setMessage(b.error||'Could not save reaction.');return}if(selected)await openThread(selected);await load()}
 async function deleteThread(){if(!selected)return;const mine=viewer.id===selected.user_id;const admin=viewer.role==='admin';if(!mine&&!admin)return;const label=selected.charge_kind==='credit'?'The 1 Forum Credit used for this thread will be returned.':'Your free-post entitlement will become available again.';if(!window.confirm(`Delete this thread?\n\n${label}\n\nAll comments and reactions on it will also be removed.`))return;setDeleteBusy(true);const t=await token();const r=await fetch(`/api/aevonsmp/forum/threads/${selected.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${t}`}});const b=await r.json();setDeleteBusy(false);if(!r.ok){setMessage(b.error||'Could not delete thread.');return}setSelected(null);setReplies([]);setWallet(b.wallet||wallet);setMessage(b.restored==='credit'?'Thread deleted. The Forum Credit used for it was returned.':'Thread deleted. Your free forum post is available again.');await load()}
 function normalizeAmount(v:number){const n=Math.max(100,Math.floor(v/10)*10);setAmount(n)}
 async function buyCredits(){setBusy(true);setMessage('');const t=await token();if(!t){setBusy(false);setMessage('Please sign in before buying forum credits.');return}const url=payMethod==='paypal'?'/api/aevonsmp/forum/credits/paypal/create':'/api/aevonsmp/forum/credits/gcash';const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({amount})});const b=await r.json();setBusy(false);if(!r.ok){setMessage(b.error||'Could not create credit top-up.');return}if(payMethod==='paypal'&&b.approveUrl){location.href=b.approveUrl;return}setCreditsOpen(false);setMessage(`GCash top-up ${b.order?.order_code} created for ${b.order?.credits} credits. Credits are added after an administrator approves the payment.`)}
 const canPost=Boolean(wallet&&(wallet.free_threads_remaining>0||wallet.credits>0));
 const postCostLabel=wallet?.free_threads_remaining? 'Your free thread is available' : '1 Forum Credit per new thread';
 const children=(parent:string|null)=>replies.filter(r=>(r.parent_reply_id||null)===parent);
 const renderReply=(r:Reply,depth=0):React.ReactNode=><div key={r.id} className="forumReplyBranch" style={{marginLeft:`${Math.min(depth,4)*22}px`}}><article className="forumReply"><AuthorBadge author={r.author}/><p>{r.body}</p><div className="forumReplyFooter"><time>{new Date(r.created_at).toLocaleString()}</time><button type="button" className="forumTextAction" disabled={!loggedIn} onClick={()=>{setReplyingTo(r);document.getElementById('forum-reply-box')?.focus()}}><MessageCircle size={12}/> Reply</button></div><ReactionBar counts={r.reaction_counts} current={r.viewer_reaction} disabled={!loggedIn} onReact={x=>void react('reply',r.id,x)}/></article>{children(r.id).map(c=>renderReply(c,depth+1))}</div>;
 return <div className="pageWrap forumPage">
  <section className="forumHero"><div><p className="eyebrow">AEVONSMP COMMUNITY</p><h1>Forum & Open Threads</h1><p className="muted">Share ideas, server stories, suggestions, guides, trades, and discussions with the AevonSMP community. Comments, comment replies, and reactions are free.</p><div className="forumHeroActions"><button className="primaryBtn" onClick={()=>{if(!loggedIn){setMessage('Please sign in to create a thread.');return}if(wallet&&!canPost){setCreditsOpen(true);return}setComposer(true)}}><Plus size={15}/> Create Thread</button><button className="secondaryBtn" onClick={()=>setCreditsOpen(true)}><Coins size={15}/> Buy Forum Credits</button><Link className="secondaryBtn" href="/aevonsmp"><Sparkles size={15}/> AevonSMP Home</Link></div></div><div className="forumWalletCard"><small>YOUR FORUM BALANCE</small><strong>{loggedIn?(wallet?.credits??0):'—'} <span>Credits</span></strong><div><span>Free post</span><b>{loggedIn?(wallet?.free_threads_remaining?'Available':'Used'):'Sign in'}</b></div><div><span>New thread price</span><b>1 Credit</b></div><div><span>Credit price</span><b>₱10</b></div><p>{postCostLabel}</p></div></section>
  {message&&<div className="notice info forumNotice">{message}</div>}
  <section className="forumRules"><div><MessagesSquare size={18}/><span><b>1 free active-thread entitlement</b><small>Delete the free thread and that free entitlement becomes available again.</small></span></div><div><Coins size={18}/><span><b>1 credit = 1 paid thread</b><small>Delete a paid thread and its 1 credit is returned to the owner.</small></span></div><div><MessageCircle size={18}/><span><b>Discussion is free</b><small>Comments, replies to comments, and reactions never consume Forum Credits.</small></span></div></section>
  <section className="forumThreadSection"><div className="sectionHeading"><div><p className="eyebrow">LATEST DISCUSSIONS</p><h2>Community Threads</h2></div><button className="secondaryBtn" onClick={load}>Refresh</button></div><div className="forumThreadList">{threads.map(t=><button className="forumThreadCard" key={t.id} onClick={()=>openThread(t)}><div className="forumThreadMain"><div className="forumThreadTitleRow">{t.is_pinned&&<span className="forumPinned">PINNED</span>}<h3>{t.title}</h3>{t.status==='locked'&&<Lock size={13}/>}</div><p>{t.body}</p><AuthorBadge author={t.author}/></div><div className="forumThreadMeta"><span><MessageCircle size={14}/>{t.reply_count||0}</span><time>{new Date(t.created_at).toLocaleDateString()}</time></div></button>)}{!threads.length&&<div className="emptyCard"><MessagesSquare size={22}/><span>No threads yet. Be the first person to start a discussion.</span></div>}</div></section>

  {composer&&<div className="asmpModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setComposer(false)}}><form className="asmpCheckoutModal forumComposer" onSubmit={createThread}><div className="sectionHeading"><div><p className="eyebrow">NEW THREAD</p><h2>Create a Forum Post</h2></div><button type="button" className="secondaryBtn" onClick={()=>setComposer(false)}><X size={14}/> Close</button></div><div className="forumCostNotice"><Coins size={16}/><span>{wallet?.free_threads_remaining?'This uses your free-post entitlement. If you later delete this thread, the free post becomes available again.':'Publishing consumes 1 Forum Credit. If you later delete this thread, that credit is returned.'}</span></div><label>Thread Title<input required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What would you like to discuss?"/></label><label>Post<textarea required maxLength={10000} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your thread here…"/></label><button className="primaryBtn forumPublishBtn" disabled={busy}>{busy?<Loader2 size={15} className="spin"/>:<Send size={15}/>} {busy?'Publishing…':'Publish Thread'}</button></form></div>}

  {creditsOpen&&<div className="asmpModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setCreditsOpen(false)}}><div className="asmpCheckoutModal forumCreditModal"><div className="sectionHeading"><div><p className="eyebrow">FORUM CREDITS</p><h2>Top Up Credits</h2></div><button className="secondaryBtn" onClick={()=>setCreditsOpen(false)}><X size={14}/> Close</button></div><div className="creditRateHero"><Coins size={25}/><div><strong>₱10 = 1 Credit</strong><span>Minimum top-up: ₱100 / 10 credits</span></div></div><div className="creditPresets">{[100,200,500,1000].map(v=><button type="button" key={v} className={amount===v?'active':''} onClick={()=>setAmount(v)}>₱{v}<small>{v/10} credits</small></button>)}</div><label>Custom Amount (PHP)<input type="number" min="100" step="10" value={amount} onChange={e=>normalizeAmount(Number(e.target.value)||100)}/><span className="fieldHint">Minimum ₱100. Amounts are accepted in ₱10 increments because each credit costs ₱10.</span></label><div className="creditCalculation"><span>You will receive</span><strong>{credits} Forum Credits</strong></div><label>Payment Method<select value={payMethod} onChange={e=>setPayMethod(e.target.value as any)}><option value="paypal">PayPal — automatic crediting</option><option value="gcash">GCash — admin verification</option></select></label><button className="primaryBtn forumPublishBtn" disabled={busy||!loggedIn} onClick={buyCredits}>{busy?<Loader2 size={15} className="spin"/>:<CreditCard size={15}/>} {busy?'Creating top-up…':!loggedIn?'Sign in to Buy Credits':payMethod==='paypal'?`Pay ₱${amount} with PayPal`:`Create ₱${amount} GCash Top-up`}</button></div></div>}

  {selected&&<div className="asmpModalBackdrop forumThreadBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="asmpCheckoutModal forumThreadModal"><div className="forumThreadModalHead"><div className="forumThreadAdminActions">{(viewer.id===selected.user_id||viewer.role==='admin')&&<button className="dangerBtn" disabled={deleteBusy} onClick={deleteThread}>{deleteBusy?<Loader2 size={14} className="spin"/>:<Trash2 size={14}/>} Delete Post</button>}</div><button className="secondaryBtn" onClick={()=>setSelected(null)}><X size={14}/> Close</button></div><article className="forumOriginalPost"><AuthorBadge author={selected.author}/><h2>{selected.title}</h2><p>{selected.body}</p><time>{new Date(selected.created_at).toLocaleString()}</time><ReactionBar counts={selected.reaction_counts} current={selected.viewer_reaction} disabled={!loggedIn} onReact={x=>void react('thread',selected.id,x)}/></article><div className="forumReplies"><h3>{replies.length} {replies.length===1?'Comment':'Comments'}</h3>{threadBusy&&!replies.length?<div className="forumLoading"><Loader2 className="spin"/> Loading thread…</div>:children(null).map(r=>renderReply(r))}</div>{selected.status==='open'?<div className="forumReplyComposer">{replyingTo&&<div className="forumReplyingTo"><span>Replying to <b>{replyingTo.author?.nickname||'Aevon Member'}</b></span><button type="button" onClick={()=>setReplyingTo(null)}><X size={12}/></button></div>}<textarea id="forum-reply-box" value={reply} onChange={e=>setReply(e.target.value)} placeholder={loggedIn?(replyingTo?'Write a reply to this comment…':'Write a comment…'):'Sign in to comment.'} disabled={!loggedIn} maxLength={6000}/><button className="primaryBtn" disabled={!loggedIn||threadBusy||!reply.trim()} onClick={sendReply}>{threadBusy?<Loader2 size={14} className="spin"/>:<Send size={14}/>} {replyingTo?'Reply to Comment':'Post Comment'}</button><small>Comments, nested replies, and reactions are free and never consume Forum Credits.</small></div>:<div className="notice info"><Lock size={15}/> This thread is locked.</div>}</div></div>}
 </div>
}
